[project]
name = "flaskproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "jinja2>=3.1.6",
    "mypy>=1.15.0",
    "python-dotenv>=1.1.0",
    "ruff>=0.11.10",
]
