"""Add Project model

Revision ID: fb866bb4a010
Revises: 1f3defc9165a
Create Date: 2025-05-24 01:39:01.409189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb866bb4a010'
down_revision = '1f3defc9165a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETE', 'IN_PROGRESS', name='projectstatus'), nullable=False),
    sa.Column('github_url', sa.String(length=2048), nullable=True),
    sa.Column('begin_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_begin_date'), ['begin_date'], unique=False)

    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_experience_start_date'), ['start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_experience_start_date'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_begin_date'))

    op.drop_table('project')
    # ### end Alembic commands ###
